#!/bin/sh
lock() {
    i3lock -c000000
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend -i
        ;;
    hibernate)
        lock && systemctl hibernate -i
        ;;
    reboot)
        systemctl reboot -i
        ;;
    shutdown)
        systemctl poweroff -i
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

