[mgr]
sort_by = "mtime"
sort_reverse = true
linemode = "mtime"

[[opener.text]]
run = 'nvim %s'
block = true
for = "unix"

[[opener.image]]
run = 'swayimg %s'
orphan = true
for = "unix"

# Plantuml generated SVG files get HTML mime type
[[plugin.prepend_previewers]]
url = "*.svg"
run = "svg"

[[open.prepend_rules]]
url = "*.svg"
use = "image"

[[open.prepend_rules]]
mime = "text/*"
use = "text"

[[open.prepend_rules]]
url = "*.txt"
use = "text"
