[mgr]
sort_by = "mtime"
sort_reverse = true
linemode = "mtime"

[[opener.text]]
run = 'nvim %s'
block = true
for = "unix"

[[open.prepend_rules]]
mime = "text/*"
use = "text"

[[open.prepend_rules]]
url = "*.txt"
use = "text"
