#!/bin/bash

# Utility to display what package changes has been done since
# the current version of documented package installation list.

rootdir=$(dirname $(readlink -f $0))

list_explicit=$(mktemp)
list_base_depends_on=$(mktemp)
list_explicit_minus_base=$(mktemp)

trap "{ rm -f \
    $list_explicit \
    $list_base_depends_on \
    $list_explicit_minus_base \
; }" EXIT

# List base package dependencies (i.e. always installed)
pacman -Sii base \
    | grep "Depends On" \
    | cut -d":" -f2 \
    | cut -b2- \
    | tr -s '[:blank:]' '\n' > "$list_base_depends_on"

# List explicitly installed packages including AUR
paru -a -Qe | cut -d" " -f1 > "$list_explicit"

# List user-installed packages without base package dependencies.
grep --fixed-strings --invert-match --line-regexp \
    --file="$list_base_depends_on" \
    "$list_explicit" \
    > "$list_explicit_minus_base"

meld "$rootdir/arch_packages.txt" "$list_explicit_minus_base"
