#!/bin/bash

# Normally, run on background, otherwise we are likely
# recovering crashed screen lock from tty
opts=

if [[ -n $WAYLAND_DISPLAY ]]; then
    opts="--daemonize"
else
    export WAYLAND_DISPLAY=wayland-1
fi

# Use --debug for additional logging
# chayang for dimming - not in use, had problems
swaylock \
    --indicator-caps-lock \
    --indicator-idle-visible \
    --color 000000 \
    $opts
