#!/bin/bash

case "$1" in
    lock)
        swaylock -f -c 000000
        ;;
	logout)
		swaymsg exit
		;;
	sleep)
		systemctl suspend
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
        echo "Invalid argument: $1"
		exit 1
esac
