#!/bin/bash

case "$1" in
    lock)
        ~/.config/sway/mylock
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
        ~/.config/sway/mylock
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Invalid argument: $1"
        exit 1
esac
