#!/bin/bash

case "$1" in
    lock)
        # let swayidle turn off display, otherwise just lock
        if pgrep -x swayidle ; then
            pkill -USR1 swayidle
        else
            swaylock -f -c 000000
        fi
        ;;
	logout)
		swaymsg exit
		;;
	suspend)
		systemctl suspend
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
        echo "Invalid argument: $1"
		exit 1
esac
